name: Pull Request Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
        cache: true
        
    - name: Install dependencies
      run: go mod download
      
    - name: Run tests
      run: go test -v ./type/...
      
    - name: Build
      run: go build ./...
      
    - name: Run example
      run: |
        cd examples
        go run audio-example.go
        
    - name: Check formatting
      run: |
        # Check if code is properly formatted
        if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
          echo "Code is not formatted. Please run 'gofmt -s -w .'"
          gofmt -s -l .
          exit 1
        fi
        
    - name: Run vet
      run: go vet ./...
      
    - name: Check for race conditions
      run: go test -race ./type/...
